### ISSUE TITLE
Sprint 2 Review

### ISSUE THREAD

**Issue by MarMansour** [UXcellent/web-app#7]
The tasks for sprint 2 were not all completed. 
The name that has been chosen is, Shine, and the logo is in the final stages of design.
A visual identity has been started, but still needs to be completely flushed out. 
Sketches for the wireframes have been created, need to be refined and made digital.

**Comment by MarMansour** [comment]
We succeeded on finding an appropriate name and an identity started. The look meets the aesthetic that we have chosen and is a good starting point to build off of. 
The majority of the tasks assigned, although started have not been completed, putting us a bit behind schedule.

**Comment by VikkieD** [comment]
We are fairly on schedule to complete this part of the project. In terms of our own schedule, we are behind but will hopefully be caught up by the end of today. We have a general logo and a name. This should be enough to get the visual design aspect done and to move into the XD prototype for next week.

**Comment by AlexandraPhilip** [comment]
We created an identity and name for the brand, along with a solid understanding on where assigned tasks go. 
The logo is started, but needs further work. The over all design and wireframes are just being started now, so we're behind our personal schedule.

**Comment by MarMansour** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
I’d like to see the Sprint reviews be more personal reflection: use "I" instead of "We".

---

Sprint 2 isn’t set up properly or followed through properly:

1. There are tasks in the project board that are still waiting to be completed.
2. Notes were used instead of Issues: each task should be a defined Issue.

See here for more details of the proper setup:
https://learn-the-web.algonquindesign.ca/courses/web-dev-6/agile-project-planning/
